apiVersion: v1 # V1 api do kubernetes
kind: ConfigMap # Tipo Config Map, configura variáveis de ambiente
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root