version: '1.0.0'  # Version of my compose file

services:
  app:
    container_name: nodejs-v18.18.0   # Container name is personal
    build: 
      context: .
      dockerfile: Dockerfile  # Redirect to Dockerfile
    volumes:
      - ./:/usr/src/app   # FROM computer root folder : TO same Dockerfile directory
    environment:
      - PORT=3000   # ENV VARIABLES for computer port, same port as shown bellow (replaces npm install dotenv)
    ports:
      - 3000:3000   # FIRST computer port : SECOND docker port
  db:
    container_name: mysql-v5.7
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: api_docker
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - 3388:3306


# TO RUN: in the docker-compose file run command: "docker-compose up"
# We can check Docker Desktop to see the container's lifecicle
# OBS: we can run the command "docker-compose up -d" so the console won't freeze in docker interface